include:
  - board: nice_nano_v2
    shield: settings_reset
    output: build/reset
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    output: build/left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    output: build/right
